name = "LinearWaves"
uuid = "f730de90-0ce9-4309-98f4-c697d77a185a"
authors = ["mcpaprota <mapap@ibwpan.gda.pl> and contributors"]
version = "1.0.0-DEV"

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"

[compat]
CairoMakie = "0.12.16"
NonlinearSolve = "4.0.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
